version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:14
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: 
        - "CMD-SHELL"
        - "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: foodgram-back
    build: ../backend/foodgram/
    env_file: .env
    volumes:
      - static:/app/collected_static/
      - media:/app/media/
      - ../data:/app/data 
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: foodgram-front
    build: ../frontend/
    command: sh -c "cp -r /app/build/. /usr/share/nginx/html/"
    env_file: .env
    volumes:
      - static:/usr/share/nginx/html/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/usr/share/nginx/html/
      - media:/usr/share/nginx/html/media/